name: Deploy

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Git commands
      run: |
        git config --global user.email "kien56162@gmail.com"
        git config --global user.name "4UT15T1Ck"
        # Install depedencies
        npm i
        # build
        npm run build
        echo 'Deploying to gh-pages...'
        git add dist -f
        git commit -m 'Deploy' 
        git push origin `git subtree split --prefix dist main`:gh-pages --force
        echo 'Done'
      env:
        github-token: ${{ secrets.VUE_TOKEN }}